### ISSUE TITLE
Collect all issue or bugzilla related to chrpath

### ISSUE THREAD

**Issue by system-thoughts** [openEuler-BaseService/chrpath#1]
This issue collect **ALL**  the issue or bugzilla related to chrpath to ensure this repo can track all the problems about chrpath.

The below comment should contain problem description and the related link. 
1. problem title use markdown link format `(problem title)[problem link]`
2. problem desciption use markdown code block format

If this problem is already solved in this repo, I will mark **solved status** of this problem. If not, I will create new issue to track this problem.

**Comment by system-thoughts** [comment]
[chrpath: strncmp: Process /usr/bin/chrpath was killed by signal 11 (SIGSEGV)](https://bugzilla.redhat.com/show_bug.cgi?id=868611)
```
Description:
Called 'chrpath --hep'  (that's a typo --hep instead of --help).
truncated backtrace:
:Thread no. 1 (4 frames)
: #0 strncmp at ../sysdeps/x86_64/strcmp.S:2112
: #1 _getopt_internal_r at getopt.c:548
: #2 _getopt_internal at getopt.c:1177
: #3 getopt_long at getopt1.c:66
```

**Comment by system-thoughts** [comment]
[This comment's issue](https://github.com/openEuler-BaseService/chrpath/issues/1#issuecomment-758359062) is already solved.

**Comment by yangzz-97** [comment]
[chrpath missing support for 32-bit binaries](https://bugzilla.redhat.com/show_bug.cgi?id=1271380)

Description of problem:
Current `chrpath` in RHEL 7 doesn't support for 32-bit executables/libraries.

**Comment by yangzz-97** [comment]
> [chrpath missing support for 32-bit binaries](https://bugzilla.redhat.com/show_bug.cgi?id=1271380)
> 
> Description:
> Current 'chrpath' in RHEL 7 do not support for 32-bit executables/libraries.

This comment's issue is already solved.

**Comment by yangzz-97** [comment]
https://github.com/openEuler-BaseService/chrpath/issues/1#issuecomment-760230428


> [chrpath missing support for 32-bit binaries](https://bugzilla.redhat.com/show_bug.cgi?id=1271380)
> 
> Description:
> Current 'chrpath' in RHEL 7 do not support for 32-bit executables/libraries.

**Comment by yangzz-97** [comment]
#https://github.com/openEuler-BaseService/chrpath/issues/1#issuecomment-760230428 
#This comment's issue is already solved.

**Comment by yangzz-97** [comment]
#https://github.com/openEuler-BaseService/chrpath/issues/1#issuecomment-760230428
This comment's issue is already solved.

**Comment by yangzz-97** [comment]
[chrpath -d won't work](https://bugs.mageia.org/show_bug.cgi?id=10949)

When building packages, we might want to drop rpath from certain binary executable. But recent upgrade of chrpath failed with:

+ chrpath -d /home/pterjan/rpmbuild/BUILDROOT/imagemagick-6.8.5.10-1.mga4.x86_64/usr/lib/perl5/vendor_perl/5.18.0/x86_64-linux-thread-multi/auto/Image/Magick/Magick.so
open: Permission denied
elf_open: Invalid argument

**Comment by yangzz-97** [comment]
#https://github.com/openEuler-BaseService/chrpath/issues/1#issuecomment-760247366
This comment's issue is already solved.

**Comment by yangzz-97** [comment]
[#2](https://github.com/openEuler-BaseService/chrpath/issues/2)
more typos in chrpath.c

**Comment by yangzz-97** [comment]
https://github.com/openEuler-BaseService/chrpath/issues/1#issuecomment-762032544
This comment's issue is already solved.

**Comment by system-thoughts** [comment]
It seems all the issues and bugzillas are covered, close this issue
